#!/bin/bash

set -eu
set -o pipefail

source ~/.nvm/nvm.sh

nvm use

npm ci

cargo fmt --all --check
cargo build --all
cargo run --bin codegen
cargo test --all
cargo clippy --all-features --fix --allow-dirty --allow-no-vcs
cargo doc

npm run check-all
