name: Validate Everything

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Setup Node.js with NVM
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Run validation script
        run: ./validate_everything
